//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_retour { get; set; }
        public int kilometrage { get; set; }
        public int ReservationId { get; set; }

        public virtual Reservation Reservation { get; set; }
    }
}
